### ISSUE TITLE
Inspect `SafeEthClient` for concurrency issues

### ISSUE THREAD

**Issue by emlautarom1** [NethermindEth/near-sffl#174]
We already found a couple of issues related to the `SafeEthClient` (see #172, #173) but there is a high chance that there are more lurking around.

We would like to revisit the code in the following package: https://github.com/NethermindEth/near-sffl/blob/8d1dc75c45cdfc9ea26169f2bd1816a597582e1f/core/safeclient/client.go

**Comment by Hyodar** [comment]
I think this is still relevant. Still, since this is probably the best place to keep this discussion, I feel like my concern on concurrency may not have been well-founded in that case. Basically, the context is these downtime issues happened close to the operators updates in kind of a random way. Still, for quite some time already things have been fine - only a short downtime in one operator and an operator that did stop tracking blocks at a point is actually running the previous version, which did exactly that.

**Comment by Hyodar** [comment]
My proposal for now is to keep an eye on the metrics (both #176 and #177 are improvements to that) and also merge #175 so we have something easier to work with. The previous reinitialization design makes things a lot harder than they need to be in an unnecessary way - what we really only needed there was resubscribing from time to time and that's it.
